### ISSUE TITLE
@ mentions with no editor button required

### ISSUE THREAD

**Issue by Zephyr-Crow** [A-Magenta-Monster/Lamia-Community#108]

**Comment by Ghost-in-the-Chel** [comment]
Unfortunately using at.js is not a practical solution for this due to various irritating issues, sooo...

https://www.youtube.com/watch?v=EzWNBmjyv7Y

Zephyr will be doing it herself.

**Comment by Ghost-in-the-Chel** [comment]
Nevermind, she realized that chasing perfection to an unnecessary degree was... well... unnecessary lol. Works beautifully.
