### ISSUE TITLE
Emoji support is probably easier than anticipated

### ISSUE THREAD

**Issue by Zephyr-Crow** [A-Magenta-Monster/Lamia-Community#112]
Use Twitter emoji library ->

> https://github.com/twitter/twemoji/blob/v2.6.0/2/72x72/1f601.png

The image names are the unicode characters to replace

For reference ->

> https://github.com/twitter/twemoji/blob/v2.6.0/2
> https://www.webpagefx.com/tools/emoji-cheat-sheet/
> http://www.unicode.org/emoji/charts/full-emoji-list.html

**Comment by Ghost-in-the-Chel** [comment]
Typing :: will pull up a searchable emoji selector for PCs, mobile users can just use their emoji keyboards.
