### ISSUE TITLE
Unable to set time zone

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#179]
Upon changing the time zone in Change Settings, and pressing submit, this error message displays.

    Theme: Not a valid choice
    Theme: Invalid theme.

This is despite there being no theme-based fields on the entire page.

Mozilla Firefox 60.0.1 64-bit for Ubuntu.

**Comment by Zephyr-Crow** [comment]
Fixed! XD
