### ISSUE TITLE
Uploading files dialogue is illegible on dark themes

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#182]
![screenshot from 2018-06-04 21-43-35](https://user-images.githubusercontent.com/13404546/40940706-907053dc-6840-11e8-9120-fee627c9df2e.png)

**Comment by Ghost-in-the-Chel** [comment]
Figures I missed something. Easy fix, though.

**Comment by Ghost-in-the-Chel** [comment]
Changed the dropzone background color, text color, and changed the active button / hovered button background/text colors to make them less terrible.
