### ISSUE TITLE
Some theme inconsistencies with multiple lines of buttons

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#183]
Apologies for the vague title.
This is hard to explain, but easy to show.
![screenshot from 2018-06-04 21-54-27](https://user-images.githubusercontent.com/13404546/40941164-fbb021f8-6841-11e8-88d0-72becd3bbe94.png)
Notice the black bar. Something to do with multiple lines of buttons?

**Comment by nectar-bluegrass** [comment]
Only an issue with dark themes.

**Comment by Ghost-in-the-Chel** [comment]
Agh, I MEANT TO FIX THIS AND FORGOT.

**Comment by Ghost-in-the-Chel** [comment]
Should be fixed, just needs to be pulled down to the site
