### ISSUE TITLE
So, uh, what should we call ourselves?

### ISSUE THREAD

**Issue by Zephyr-Crow** [A-Magenta-Monster/Lamia-Community#185]
This is a really bizarre issue, but I realize that our nomenclature for referring to lamia isn't actually standardized.

I'm just wondering... What are we?

Are we... A community platform? A forum? A social network? ^^;;;;

**Comment by nectar-bluegrass** [comment]
"Internet community software" I think.
Wikipedia seems to think so, also.
"Community platform" sounds very strong to me too though!

**Comment by Zephyr-Crow** [comment]
I think that I'm actually in favor of "community platform" too, so let's go with that. XD
