### ISSUE TITLE
Navbar display on 4" phones is wonky

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#186]
![img_1027](https://user-images.githubusercontent.com/13404546/40984733-82fdffd4-68da-11e8-869d-856bd150c3c2.PNG)
Is this realistic to fix?
From what I understand 4" phones are still in very frequent use globally.
I went looking for official statistics but couldn't find any XD
Anyway! Please support 4" screens and make everything line up all neat :3

**Comment by Zephyr-Crow** [comment]
This might be fixed with the upcoming rewrite, but only if we remember to
fix it while doing the rewrite. XD

**Comment by Ghost-in-the-Chel** [comment]
@nectar-bluegrass 

I've addressed the issue with some media queries. Just before the screen becomes small enough for that to happen, the profile link (avatar) button will be removed, making everything fit. You'll still have a profile link in the drop-down navigation bar.

It isn't live atm, but it should resolve this.
