### ISSUE TITLE
Profile buttons look funky on mobile

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#187]
![img_1028](https://user-images.githubusercontent.com/13404546/40990695-9256f940-68e9-11e8-97b2-4176bf0afdd5.jpg)

**Comment by Zephyr-Crow** [comment]
Hahaha, yeah I have no idea how that... Even happened... ^^;

**Comment by Ghost-in-the-Chel** [comment]
I've identified a good path forward for this, but probably won't get around to implementing it until tomorrow. Way too tired to be digging into the templates atm, lol.
