### ISSUE TITLE
Make text editors stretchy

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#188]
This would be a nice feature!
Resizable editors would mean you can see more of what you're writing at once, and that's super neat.

**Comment by Zephyr-Crow** [comment]
Is this not a thing?!

**Comment by nectar-bluegrass** [comment]
Not for blog entries.
It is for status updates. Haven't checked for threads yet.

**Comment by Ghost-in-the-Chel** [comment]
iirc we might have ran into some issues trying to do this in the past(?), but that was would have been on a much - much - earlier verison of Quill if it was the case

**Comment by Ghost-in-the-Chel** [comment]
o. I already fixed this, I just forgot to reference the issue in the commit description.

vertical resizing should work perfectly once the changes are pulled tonight
