### ISSUE TITLE
Blog drafts are illegible on dark theme

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#189]
Sorry Chel, hahaha ^-^;
![screenshot from 2018-06-05 18-46-51](https://user-images.githubusercontent.com/13404546/40993579-e41ce480-68f1-11e8-8a62-fb20b7cb4c35.png)

**Comment by nectar-bluegrass** [comment]
Well, nearly illegible.

**Comment by Ghost-in-the-Chel** [comment]
Fixed! Isn't live yet, however.
