### ISSUE TITLE
More options for Text/image wrapping

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#191]
This is a request.
Tight text/image wrapping (amongst other types) would be very nice for putting images in-line of about mes, blogs and threads. At the moment, only one line of text may accompany an image at the side of it regardless of size. It is essentially treated like a large single character, which would be nice to change.
Not sure if this is possible atm, since I believe, iirc, that the text editor is a separate plugin.

**Comment by Zephyr-Crow** [comment]
Use the :wrap option at the end of an image attachment, I think that it
would do what you're talking about. 🤔

**Comment by Ghost-in-the-Chel** [comment]
Yeah, it's the :wrap option - I just ran to confirm. It's an undocumented feature atm

**Comment by Ghost-in-the-Chel** [comment]
[attachment=(attachment number):(width):wrap]

**Comment by nectar-bluegrass** [comment]
Thank you! <3
