### ISSUE TITLE
Some member profile links are broken

### ISSUE THREAD

**Issue by Ghost-in-the-Chel** [A-Magenta-Monster/Lamia-Community#193]
Case in point: https://lamiacommunity.com/member/wreck-it ralph

should be

https://lamiacommunity.com/member/wreck-it-ralph

**Comment by Zephyr-Crow** [comment]
Which links specifically are broken? :?

**Comment by Ghost-in-the-Chel** [comment]
Clicking ralph's name on forum posts and status updates brings up the former of the two

**Comment by Zephyr-Crow** [comment]
... o

So uh, I think that this was working and then I broke it, hahaha. XD

Regressions! This is why we have tests.
