### ISSUE TITLE
Threads report that they have 1 more reply than they do

### ISSUE THREAD

**Issue by nectar-bluegrass** [A-Magenta-Monster/Lamia-Community#256]
For example, topics with 4 replies will report that they have 5.
Newly created threads say they have 1 'replies', which itself is its own issue x3
Hardly the most pressing issue, toss this to the bottom of the pile ^w^

**Comment by Zephyr-Crow** [comment]
Is it counting the opening post as a reply perhaps?

**Comment by nectar-bluegrass** [comment]
It is yes, but should it, is the point I'm making
Since what is it a reply to? :P

**Comment by Zephyr-Crow** [comment]
Clearly it's uhhhh, a reply to the abstract theory of discussion....
Errrr... I'm gonna need to fix this, I think, hahaha

**Comment by nectar-bluegrass** [comment]
Hahahaha, perfect answer XD

**Comment by Zephyr-Crow** [comment]
I actually resolved this structurally in Lamia 2.

Rather than the initial post in a thread being a post, it will now just be the thread itself. Which... Makes sense, because you can't have a thread without the opening post.
