### ISSUE TITLE
Status updates/comments should be editable by staff

### ISSUE THREAD

**Issue by Ghost-in-the-Chel** [A-Magenta-Monster/Lamia-Community#77]

**Comment by Scarly-Crow** [comment]
Chel, currently this works by clicking the little gear icon, which provides access to the raw contents of a status update.

Is that fine?

**Comment by Ghost-in-the-Chel** [comment]
Yeah, I think that more than covers it... I don't really see a reason to do anything fancier. Honestly in most cases it makes more sense to just hide the things outright than to selectively edit them, I'd say.
