### ISSUE TITLE
Auto merge double posts

### ISSUE THREAD

**Issue by Ghost-in-the-Chel** [A-Magenta-Monster/Lamia-Community#85]

**Comment by Scarly-Crow** [comment]
This should probably be a configurable option somewhere?

**Comment by Ghost-in-the-Chel** [comment]
Skipping this, to be honest. Isn't really necessary and adds little value. The edit function exists for a reason, and honestly an occasional and reasonable double post shouldn't be considered a bad thing.

**Comment by GoldenChaos** [comment]
I think this option is useful because it prevents accidental double posts. But maybe that’s another thing.

**Comment by Ghost-in-the-Chel** [comment]
Lamia actually has protection against accidental double posts built into the back end :3

**Comment by GoldenChaos** [comment]
Okie! Yey 😬
